version: '3'
services:

  employee-db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"

  employee-service:
    image: marcinjachymek/employee-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: employee-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - employee-db
